### ISSUE TITLE
Ruby 2.2 uninitialized constant HTTP::Timeout::PerOperation::Resolv (NameError)

### ISSUE THREAD

**Issue by pxlpnk** [httprb/http.rb#202]
Using Ruby 2.2.{0,1} and http.rb results in the following error:

```
/Users/at/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:4:in `<class:PerOperation>': uninitialized constant HTTP::Timeout::PerOperation::Resolv (NameError)
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:3:in `<module:Timeout>'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:2:in `<module:HTTP>'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/http-0.8.0/lib/http/timeout/per_operation.rb:1:in `<top (required)>'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/http-0.8.0/lib/http.rb:5:in `<top (required)>'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/at/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from http_bug.rb:2:in `<main>'
```

This can be reproduced by either using `require 'http'` in a script or directly in pry/irb.
It does not happen in Ruby 2.1

**Comment by ixti** [comment]
Thanks for report!

**Comment by ixti** [comment]
As a workaround you can explicitly `require "resolv"` before `require "http"`. I'm gonna cut a patch release soon though...

**Comment by pxlpnk** [comment]
Great. Thank you very much. Great response time (:
